export const brand = {
  name: "Stickerfizzbd",
  displayName: "Stickerfizzbd",
  logo: "/stickerfizzbd-logo.png",
  followers: "6.2K followers",
  tagline: "We turn ideas into reality",
  sparkleTagline: "We turn ideas into reality",
  description: "Premium custom stickers & decals",
  quality: "Quality guaranteed",
  orderPrompt: "Message us to order",
  service: "Printing service",
  priceSignal: "Premium pricing",
  email: "stickerfizzbd@gmail.com",
  phone: "+880 1307-910224",
  instagram: "stickerfizzbd",
  facebook: "Stickerfizzbd",
  facebookUrl: "https://facebook.com/profile.php?id=61584629323897",
  externalLink: "google.com",
};
