export type Product = {
  id: string;
  title: string;
  slug: string;
  category: string;
  type: "case" | "sticker";
  price: number;
  oldPrice?: number;
  description: string;
  image: string;
  images: string[];
  featured?: boolean;
  stock: number;
  tags: string[];
  rating: number;
};

export const STICKER_PRICE_PER_SQ_INCH = 13;
export const PHONE_CASE_PRICE = 600;

export const categories = [
  'Phone Cases',
  'Anime Stickers',
  'Car & Racing Stickers',
  'Cute & Meme Stickers',
];

export const products: Product[] = [
  {
    id: 'case-01',
    title: 'Custom Phone Case BAN',
    slug: 'phone-case-ban',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case BAN with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/ban.jpg',
    images: ['/products/phone-cases/ban.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-02',
    title: 'Custom Phone Case BAT',
    slug: 'phone-case-bat',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case BAT with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/bat.jpg',
    images: ['/products/phone-cases/bat.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-03',
    title: 'Custom Phone Case BG',
    slug: 'phone-case-bg',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case BG with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/bg.jpg',
    images: ['/products/phone-cases/bg.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-04',
    title: 'Custom Phone Case BL',
    slug: 'phone-case-bl',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case BL with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/bl.jpg',
    images: ['/products/phone-cases/bl.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-05',
    title: 'Custom Phone Case CA',
    slug: 'phone-case-ca',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case CA with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/ca.jpg',
    images: ['/products/phone-cases/ca.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-06',
    title: 'Custom Phone Case CDS',
    slug: 'phone-case-cds',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case CDS with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/cds.jpg',
    images: ['/products/phone-cases/cds.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-07',
    title: 'Custom Phone Case CR',
    slug: 'phone-case-cr',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case CR with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/cr.jpg',
    images: ['/products/phone-cases/cr.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-08',
    title: 'Custom Phone Case DF',
    slug: 'phone-case-df',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case DF with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/df.jpg',
    images: ['/products/phone-cases/df.jpg'],
    featured: true,
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-09',
    title: 'Custom Phone Case DFG',
    slug: 'phone-case-dfg',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case DFG with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/dfg.jpg',
    images: ['/products/phone-cases/dfg.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-10',
    title: 'Custom Phone Case DFGK',
    slug: 'phone-case-dfgk',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case DFGK with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/dfgk.jpg',
    images: ['/products/phone-cases/dfgk.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-11',
    title: 'Custom Phone Case FG',
    slug: 'phone-case-fg',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case FG with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/fg.jpg',
    images: ['/products/phone-cases/fg.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-12',
    title: 'Custom Phone Case FIRE',
    slug: 'phone-case-fire',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case FIRE with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/fire.jpg',
    images: ['/products/phone-cases/fire.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-13',
    title: 'Custom Phone Case GT',
    slug: 'phone-case-gt',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case GT with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/gt.jpg',
    images: ['/products/phone-cases/gt.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-14',
    title: 'Custom Phone Case H',
    slug: 'phone-case-h',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case H with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/h.jpg',
    images: ['/products/phone-cases/h.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-15',
    title: 'Custom Phone Case HGFD',
    slug: 'phone-case-hgfd',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case HGFD with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/hgfd.jpg',
    images: ['/products/phone-cases/hgfd.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-16',
    title: 'Custom Phone Case HGFDKJ',
    slug: 'phone-case-hgfdkj',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case HGFDKJ with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/hgfdkj.jpg',
    images: ['/products/phone-cases/hgfdkj.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-17',
    title: 'Custom Phone Case HGFDS',
    slug: 'phone-case-hgfds',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case HGFDS with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/hgfds.jpg',
    images: ['/products/phone-cases/hgfds.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-18',
    title: 'Custom Phone Case HJ',
    slug: 'phone-case-hj',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case HJ with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/hj.jpg',
    images: ['/products/phone-cases/hj.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-19',
    title: 'Custom Phone Case HK',
    slug: 'phone-case-hk',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case HK with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/hk.jpg',
    images: ['/products/phone-cases/hk.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-20',
    title: 'Custom Phone Case JHGFD',
    slug: 'phone-case-jhgfd',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case JHGFD with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/jhgfd.jpg',
    images: ['/products/phone-cases/jhgfd.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-21',
    title: 'Custom Phone Case JHGFDF',
    slug: 'phone-case-jhgfdf',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case JHGFDF with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/jhgfdf.jpg',
    images: ['/products/phone-cases/jhgfdf.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-22',
    title: 'Custom Phone Case K',
    slug: 'phone-case-k',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case K with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/k.jpg',
    images: ['/products/phone-cases/k.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-23',
    title: 'Custom Phone Case L',
    slug: 'phone-case-l',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case L with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/l.jpg',
    images: ['/products/phone-cases/l.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-24',
    title: 'Custom Phone Case M1',
    slug: 'phone-case-m1',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M1 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m1.jpg',
    images: ['/products/phone-cases/m1.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-25',
    title: 'Custom Phone Case M10',
    slug: 'phone-case-m10',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M10 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m10.jpg',
    images: ['/products/phone-cases/m10.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-26',
    title: 'Custom Phone Case M11',
    slug: 'phone-case-m11',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M11 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m11.jpg',
    images: ['/products/phone-cases/m11.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-27',
    title: 'Custom Phone Case M12',
    slug: 'phone-case-m12',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M12 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m12.jpg',
    images: ['/products/phone-cases/m12.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-28',
    title: 'Custom Phone Case M17',
    slug: 'phone-case-m17',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M17 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m17.jpg',
    images: ['/products/phone-cases/m17.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-29',
    title: 'Custom Phone Case M19',
    slug: 'phone-case-m19',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M19 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m19.jpg',
    images: ['/products/phone-cases/m19.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-30',
    title: 'Custom Phone Case M2',
    slug: 'phone-case-m2',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M2 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m2.jpg',
    images: ['/products/phone-cases/m2.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-31',
    title: 'Custom Phone Case M21',
    slug: 'phone-case-m21',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M21 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m21.jpg',
    images: ['/products/phone-cases/m21.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-32',
    title: 'Custom Phone Case M22',
    slug: 'phone-case-m22',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M22 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m22.jpg',
    images: ['/products/phone-cases/m22.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-33',
    title: 'Custom Phone Case M23',
    slug: 'phone-case-m23',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M23 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m23.jpg',
    images: ['/products/phone-cases/m23.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-34',
    title: 'Custom Phone Case M24',
    slug: 'phone-case-m24',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M24 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m24.jpg',
    images: ['/products/phone-cases/m24.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-35',
    title: 'Custom Phone Case M25',
    slug: 'phone-case-m25',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M25 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m25.jpg',
    images: ['/products/phone-cases/m25.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-36',
    title: 'Custom Phone Case M26',
    slug: 'phone-case-m26',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M26 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m26.jpg',
    images: ['/products/phone-cases/m26.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-37',
    title: 'Custom Phone Case M3',
    slug: 'phone-case-m3',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M3 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m3.jpg',
    images: ['/products/phone-cases/m3.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-38',
    title: 'Custom Phone Case M4',
    slug: 'phone-case-m4',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M4 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m4.jpg',
    images: ['/products/phone-cases/m4.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-39',
    title: 'Custom Phone Case M5',
    slug: 'phone-case-m5',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M5 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m5.jpg',
    images: ['/products/phone-cases/m5.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-40',
    title: 'Custom Phone Case M6',
    slug: 'phone-case-m6',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M6 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m6.jpg',
    images: ['/products/phone-cases/m6.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-41',
    title: 'Custom Phone Case M7',
    slug: 'phone-case-m7',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M7 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m7.jpg',
    images: ['/products/phone-cases/m7.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-42',
    title: 'Custom Phone Case M8',
    slug: 'phone-case-m8',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M8 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m8.jpg',
    images: ['/products/phone-cases/m8.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-43',
    title: 'Custom Phone Case M9',
    slug: 'phone-case-m9',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case M9 with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/m9.jpg',
    images: ['/products/phone-cases/m9.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-44',
    title: 'Custom Phone Case MK',
    slug: 'phone-case-mk',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case MK with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/mk.jpg',
    images: ['/products/phone-cases/mk.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-45',
    title: 'Custom Phone Case RB',
    slug: 'phone-case-rb',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case RB with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/rb.jpg',
    images: ['/products/phone-cases/rb.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-46',
    title: 'Custom Phone Case RCG',
    slug: 'phone-case-rcg',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case RCG with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/rcg.jpg',
    images: ['/products/phone-cases/rcg.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-47',
    title: 'Custom Phone Case RS',
    slug: 'phone-case-rs',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case RS with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/rs.jpg',
    images: ['/products/phone-cases/rs.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-48',
    title: 'Custom Phone Case RTY',
    slug: 'phone-case-rty',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case RTY with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/rty.jpg',
    images: ['/products/phone-cases/rty.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-49',
    title: 'Custom Phone Case SDFG',
    slug: 'phone-case-sdfg',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case SDFG with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/sdfg.jpg',
    images: ['/products/phone-cases/sdfg.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'case-50',
    title: 'Custom Phone Case VBNM',
    slug: 'phone-case-vbnm',
    category: 'Phone Cases',
    type: 'case',
    price: 600,
    oldPrice: 750,
    description: 'Custom Phone Case VBNM with Stickerfizzbd artwork. All phone cases are fixed price Tk 600.',
    image: '/products/phone-cases/vbnm.jpg',
    images: ['/products/phone-cases/vbnm.jpg'],
    stock: 25,
    tags: ['Phone Case', 'Tk 600', 'Custom Print'],
    rating: 4.9,
  },
  {
    id: 'sticker-01',
    title: 'Attack On Titan Sticker Sheet',
    slug: 'sticker-attack',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Attack On Titan Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/attack.jpg',
    images: ['/products/stickers/attack.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-02',
    title: 'Berserk Anime Sticker Sheet',
    slug: 'sticker-bar',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Berserk Anime Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/bar.jpg',
    images: ['/products/stickers/bar.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-03',
    title: 'Black Clover Sticker Sheet',
    slug: 'sticker-blackclover',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Black Clover Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/blackclover.jpg',
    images: ['/products/stickers/blackclover.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-04',
    title: 'Bleach Sticker Sheet',
    slug: 'sticker-bleach',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Bleach Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/bleach.jpg',
    images: ['/products/stickers/bleach.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-05',
    title: 'Supra Car Sticker Sheet',
    slug: 'sticker-car-2',
    category: 'Car & Racing Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Supra Car Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/car-2.jpg',
    images: ['/products/stickers/car-2.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Car & Racing', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-06',
    title: 'JDM Car Sticker Sheet',
    slug: 'sticker-car',
    category: 'Car & Racing Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'JDM Car Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/car.jpg',
    images: ['/products/stickers/car.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Car & Racing', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-07',
    title: 'Chainsaw Man Sticker Sheet',
    slug: 'sticker-chainsawman',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Chainsaw Man Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/chainsawman.jpg',
    images: ['/products/stickers/chainsawman.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-08',
    title: 'Dandadan Sticker Sheet',
    slug: 'sticker-dandandan',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Dandadan Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/dandandan.jpg',
    images: ['/products/stickers/dandandan.jpg'],
    featured: true,
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-09',
    title: 'Death Note Sticker Sheet',
    slug: 'sticker-death',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Death Note Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/death.jpg',
    images: ['/products/stickers/death.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-10',
    title: 'Demon Slayer Sticker Sheet',
    slug: 'sticker-demon',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Demon Slayer Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/demon.jpg',
    images: ['/products/stickers/demon.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-11',
    title: 'Dragon Ball Sticker Sheet',
    slug: 'sticker-dragonball',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Dragon Ball Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/dragonball.jpg',
    images: ['/products/stickers/dragonball.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-12',
    title: 'F1 Racing Sticker Sheet',
    slug: 'sticker-f1',
    category: 'Car & Racing Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'F1 Racing Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/f1.jpg',
    images: ['/products/stickers/f1.jpg'],
    stock: 80,
    tags: ['Sticker', 'Car & Racing', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-13',
    title: 'Fire Force Sticker Sheet',
    slug: 'sticker-fireforce',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Fire Force Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/fireforce.jpg',
    images: ['/products/stickers/fireforce.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-14',
    title: 'Hello Kitty Sticker Sheet',
    slug: 'sticker-hello-kitty',
    category: 'Cute & Meme Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Hello Kitty Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/hello-kitty.jpg',
    images: ['/products/stickers/hello-kitty.jpg'],
    stock: 80,
    tags: ['Sticker', 'Cute & Meme', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-15',
    title: 'Hunter x Hunter Sticker Sheet',
    slug: 'sticker-hunterx',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Hunter x Hunter Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/hunterx.jpg',
    images: ['/products/stickers/hunterx.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-16',
    title: 'Jujutsu Kaisen Sticker Sheet',
    slug: 'sticker-jjk-sticker',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Jujutsu Kaisen Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/jjk-sticker.jpg',
    images: ['/products/stickers/jjk-sticker.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-17',
    title: 'Kaiju No. 8 Sticker Sheet',
    slug: 'sticker-kaiju-8',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Kaiju No. 8 Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/kaiju-8.jpg',
    images: ['/products/stickers/kaiju-8.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-18',
    title: 'Kuromi Sticker Sheet',
    slug: 'sticker-kuromi',
    category: 'Cute & Meme Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Kuromi Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/kuromi.jpg',
    images: ['/products/stickers/kuromi.jpg'],
    stock: 80,
    tags: ['Sticker', 'Cute & Meme', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-19',
    title: 'Mashle Sticker Sheet',
    slug: 'sticker-mash',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Mashle Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/mash.jpg',
    images: ['/products/stickers/mash.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-20',
    title: 'Meme Sticker Sheet',
    slug: 'sticker-meme',
    category: 'Cute & Meme Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Meme Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/meme.jpg',
    images: ['/products/stickers/meme.jpg'],
    stock: 80,
    tags: ['Sticker', 'Cute & Meme', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-21',
    title: 'My Hero Academia Sticker Sheet',
    slug: 'sticker-my-hero',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'My Hero Academia Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/my-hero.png',
    images: ['/products/stickers/my-hero.png'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-22',
    title: 'Naruto Sticker Sheet',
    slug: 'sticker-naruto',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Naruto Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/naruto.png',
    images: ['/products/stickers/naruto.png'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-23',
    title: 'One Piece Sticker Sheet',
    slug: 'sticker-one-piece',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'One Piece Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/one-piece.jpg',
    images: ['/products/stickers/one-piece.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-24',
    title: 'One Punch Man Sticker Sheet',
    slug: 'sticker-one-punch',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'One Punch Man Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/one-punch.jpg',
    images: ['/products/stickers/one-punch.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-25',
    title: 'Pink Panther Sticker Sheet',
    slug: 'sticker-pink',
    category: 'Cute & Meme Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Pink Panther Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/pink.jpg',
    images: ['/products/stickers/pink.jpg'],
    stock: 80,
    tags: ['Sticker', 'Cute & Meme', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-26',
    title: 'Powerpuff Girls Sticker Sheet',
    slug: 'sticker-power',
    category: 'Cute & Meme Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Powerpuff Girls Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/power.jpg',
    images: ['/products/stickers/power.jpg'],
    stock: 80,
    tags: ['Sticker', 'Cute & Meme', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-27',
    title: 'Shinchan Sticker Sheet',
    slug: 'sticker-shinchan',
    category: 'Cute & Meme Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Shinchan Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/shinchan.jpg',
    images: ['/products/stickers/shinchan.jpg'],
    stock: 80,
    tags: ['Sticker', 'Cute & Meme', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-28',
    title: 'Solo Leveling Sticker Sheet',
    slug: 'sticker-solo',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Solo Leveling Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/solo.jpg',
    images: ['/products/stickers/solo.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-29',
    title: 'Spy x Family Sticker Sheet',
    slug: 'sticker-spyx',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Spy x Family Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/spyx.jpg',
    images: ['/products/stickers/spyx.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
  {
    id: 'sticker-30',
    title: 'Vinland Saga Sticker Sheet',
    slug: 'sticker-vindland',
    category: 'Anime Stickers',
    type: 'sticker',
    price: 117,
    oldPrice: 150,
    description: 'Vinland Saga Sticker Sheet for laptops, bottles, journals, rooms, and custom packs. Sticker price is calculated at Tk 13 per square inch.',
    image: '/products/stickers/vindland.jpg',
    images: ['/products/stickers/vindland.jpg'],
    stock: 80,
    tags: ['Sticker', 'Anime', 'Tk 13 per sq inch'],
    rating: 4.8,
  },
];

export function formatTaka(amount: number) {
  return `Tk ${amount.toLocaleString("en-BD")}`;
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getRelatedProducts(product: Product) {
  return products
    .filter(
      (item) =>
        item.id !== product.id &&
        (item.category === product.category || item.type === product.type),
    )
    .slice(0, 3);
}
